import { Center } from '@mantine/core';
import Head from 'next/head';
import HomeHeader from '../components/HomeHeader';

export default function Home() {
  return (
    <>
      <Head>
        <title>مونده</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeHeader />
    </>
  );
}
