import Head from 'next/head';

import { MediaQuery, Divider, Space } from '@mantine/core';

import MainLayout from '../layouts/MainLayout';

import CardsContainer from '../components/CardsContainer';
import SearchInput from '../components/SearchInput';

const Home = () => {
  return (
    <>
      <Head>
        <title>مونده</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>
        <Space h={10} />
        <MediaQuery largerThan="sm" styles={{ display: 'none' }}>
          <SearchInput inputWidth="100%" />
        </MediaQuery>
        <MediaQuery largerThan="sm" styles={{ display: 'none' }}>
          <Divider
            mt={25}
            mb={20}
            label="رویداد ها"
            labelPosition="center"
            variant="dashed"
          />
        </MediaQuery>
        <CardsContainer />
      </MainLayout>
    </>
  );
};

export default Home;
